apiVersion: v1
kind: Secret
metadata:
  name: another-secret
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: argocd
type: Opaque
data:
  # Store client secret like below.
  # Ensure the secret is base64 encoded
  oidc.auth0.clientSecret: c2VjcmV0Cg==
