apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Nizar-opt/playground.git
    targetRevision: HEAD
    path:  .
    helm:
      parameters:
      - name: secret
        value: mysecret
      valueFiles:
      - values.yaml
  destination:
    name: app
    namespace: default
