apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm2
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm2
    app.kubernetes.io/part-of: argocd
data:
  oidc.config: |
    name: Auth0
    clientID: aabbccddeeff00112233
    # Reference key in another-secret (and not argocd-secret)
    clientSecret: $another-secret:oidc.auth0.clientSecret  # Mind the ':'