apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
    - name: {{index .Values "file.me" "name"}}
      image: busybox
      command:
        - /bin/sh -c
      args:
        - echo {{ .Values.secret }}
